/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.NhaXuatBan;
import Entity.NhaCungCap;
import DAO.NhaXuatBanDAO;
import DAO.NhaCungCapDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;
import utils.XHeper;

/**
 *
 * @author Lân Hồ
 */
public class NhaXBvsCC extends javax.swing.JPanel {

    private int index;
    private NhaXuatBanDAO daoNXB = new NhaXuatBanDAO();
    private NhaCungCapDAO dao2 = new NhaCungCapDAO();
    private DefaultTableModel model = new DefaultTableModel();
    private List<NhaXuatBan> listNXB = new ArrayList<>();
    private List<NhaCungCap> list2 = new ArrayList<>();

    public NhaXBvsCC() {
        this.initComponents();
        this.init();
    }

//    private void init() {
//        fillTableNXB();
//        fillTableNCC();
//    }
    private void init() {
        this.fillTableNXB();
        this.fillTableNCC();
        this.index = -1;
        this.updateStatus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setForm(NhaXuatBan nxb) {
        this.txtTenNXB.setText(nxb.getTenNhaXB());
        this.txtDiachiNXB.setText(nxb.getDiaChi());
        this.txtSDTNXB.setText(nxb.getSDT());
        if (nxb.isTrangThai() == 1) {
            rdoHDNXB.setSelected(true);
        } else {
            rdoUnHDNXB.setSelected(true);
        }
    }

    private void setFormNCC(NhaCungCap ncc) {
        this.txtTenNCC.setText(ncc.getTenNhaCP());
        this.txtDiachiNCC.setText(ncc.getDiaChi());
        this.txtSDTNCC.setText(ncc.getSDT());
        if (ncc.isTrangThai() == 1) {
            rdoHDNCC.setSelected(true);
        } else {
            rdoUnHDNCC.setSelected(true);
        }
    }

    private NhaXuatBan getFormNXB() {
        NhaXuatBan nxb = new NhaXuatBan();
        nxb.setTenNhaXB(this.txtTenNXB.getText());
        nxb.setDiaChi(this.txtDiachiNXB.getText());
        nxb.setSDT(this.txtSDTNXB.getText());
        nxb.setTrangThai(this.rdoHDNXB.isSelected() ? 1 : 0);
        return nxb;
    }

    private NhaCungCap getFormNCC() {
        NhaCungCap ncc = new NhaCungCap();
        ncc.setTenNhaCP(this.txtTenNCC.getText());
        ncc.setDiaChi(this.txtDiachiNCC.getText());
        ncc.setSDT(this.txtSDTNCC.getText());
        ncc.setTrangThai(this.rdoHDNCC.isSelected() ? 1 : 0);
        return ncc;
    }

    private void showInforNXB() {
        String TenNXB = (String) tblNXB.getValueAt(this.index, 0);
        NhaXuatBan nxb = daoNXB.selectById(TenNXB);
        this.setForm(nxb);
    }

    private void showInforNCC() {
        String TenNCC = (String) tblNCC2.getValueAt(this.index, 0);
        NhaCungCap ncc = dao2.selectById(TenNCC);
        this.setFormNCC(ncc);
    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(KhachHangFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(KhachHangFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(KhachHangFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(KhachHangFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NhaXBvsCC().setVisible(true);
//            }
//        });
//    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Jbody = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblNXB = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        rdoHDNXB = new javax.swing.JRadioButton();
        rdoUnHDNXB = new javax.swing.JRadioButton();
        txtSDTNXB = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtDiachiNXB = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtTenNXB = new javax.swing.JTextField();
        btnClearNXB = new javax.swing.JButton();
        btnInsertNXB = new javax.swing.JButton();
        btnUpdateNXB = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        txtDiachiNCC = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtSDTNCC = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        rdoHDNCC = new javax.swing.JRadioButton();
        rdoUnHDNCC = new javax.swing.JRadioButton();
        btnInsertNCC = new javax.swing.JButton();
        btnUpdateNCC = new javax.swing.JButton();
        btnClearNCC = new javax.swing.JButton();
        btnDeleteNCC = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblNCC2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        setLayout(new java.awt.BorderLayout());

        Jbody.setBackground(new java.awt.Color(51, 204, 255));

        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Nhà Xuất Bản", "Địa Chỉ", "Số Điện Thoạii", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNXBMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblNXB);

        jLabel26.setText("Trạng Thái");

        jLabel27.setText("Số Điện Thoại");

        buttonGroup1.add(rdoHDNXB);
        rdoHDNXB.setSelected(true);
        rdoHDNXB.setText("Đang Hoạt Động");
        rdoHDNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHDNXBActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoUnHDNXB);
        rdoUnHDNXB.setText("Đang Ẩn");
        rdoUnHDNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoUnHDNXBActionPerformed(evt);
            }
        });

        txtSDTNXB.setName("số điện thoại"); // NOI18N
        txtSDTNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTNXBActionPerformed(evt);
            }
        });

        jLabel28.setText("Địa Chỉ");

        txtDiachiNXB.setName("địa chỉ"); // NOI18N
        txtDiachiNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiachiNXBActionPerformed(evt);
            }
        });

        jLabel29.setText("Tên Nhà Xuất Bản");

        txtTenNXB.setName("tên nhà xuất bản"); // NOI18N
        txtTenNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNXBActionPerformed(evt);
            }
        });

        btnClearNXB.setText("Mới");
        btnClearNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNXBActionPerformed(evt);
            }
        });

        btnInsertNXB.setText("Thêm");
        btnInsertNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNXBActionPerformed(evt);
            }
        });

        btnUpdateNXB.setText("Sửa");
        btnUpdateNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNXBActionPerformed(evt);
            }
        });

        jLabel30.setText("Tên Nhà Cung Cấp");

        txtTenNCC.setName("tên nhà cung cấp"); // NOI18N
        txtTenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNCCActionPerformed(evt);
            }
        });

        txtDiachiNCC.setName("địa chỉ"); // NOI18N
        txtDiachiNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiachiNCCActionPerformed(evt);
            }
        });

        jLabel31.setText("Địa Chỉ");

        jLabel32.setText("Số Điện Thoại");

        txtSDTNCC.setName("số điện thoại"); // NOI18N
        txtSDTNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTNCCActionPerformed(evt);
            }
        });

        jLabel33.setText("Trạng Thái");

        buttonGroup2.add(rdoHDNCC);
        rdoHDNCC.setSelected(true);
        rdoHDNCC.setText("Đang Hoạt Dộng");
        rdoHDNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHDNCCActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoUnHDNCC);
        rdoUnHDNCC.setText("Đang Ẩn");

        btnInsertNCC.setText("Thêm");
        btnInsertNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNCCActionPerformed(evt);
            }
        });

        btnUpdateNCC.setText("Sửa");
        btnUpdateNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNCCActionPerformed(evt);
            }
        });

        btnClearNCC.setText("Mới");
        btnClearNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearNCCActionPerformed(evt);
            }
        });

        btnDeleteNCC.setText("Hiển thị tất cả");
        btnDeleteNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNCCActionPerformed(evt);
            }
        });

        btnShowAll.setText("Hiển thị tất cả");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tblNCC2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Nhà Cung Cấp", "Địa Chỉ", "Số Điện Thoạii", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNCC2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCC2MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblNCC2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nhà Cung Cấp");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nhà Xuất Bản");

        javax.swing.GroupLayout JbodyLayout = new javax.swing.GroupLayout(Jbody);
        Jbody.setLayout(JbodyLayout);
        JbodyLayout.setHorizontalGroup(
            JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(JbodyLayout.createSequentialGroup()
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoHDNXB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoUnHDNXB))
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(rdoHDNCC)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoUnHDNCC))
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JbodyLayout.createSequentialGroup()
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JbodyLayout.createSequentialGroup()
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtDiachiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(73, 73, 73)
                                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnInsertNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnClearNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUpdateNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDeleteNCC)))))
                            .addComponent(jLabel1)))
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JbodyLayout.createSequentialGroup()
                                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addComponent(txtDiachiNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnInsertNXB))
                                    .addGroup(JbodyLayout.createSequentialGroup()
                                        .addComponent(txtSDTNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(btnUpdateNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnShowAll)
                                    .addComponent(btnClearNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JbodyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(583, Short.MAX_VALUE))
        );

        JbodyLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClearNCC, btnClearNXB, btnDeleteNCC, btnInsertNCC, btnInsertNXB, btnShowAll, btnUpdateNCC, btnUpdateNXB});

        JbodyLayout.setVerticalGroup(
            JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JbodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachiNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(btnInsertNXB)
                    .addComponent(btnClearNXB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDTNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(btnShowAll)
                    .addComponent(btnUpdateNXB))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdoHDNXB)
                    .addComponent(rdoUnHDNXB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtDiachiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertNCC)
                    .addComponent(btnUpdateNCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDTNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearNCC)
                    .addComponent(btnDeleteNCC))
                .addGap(18, 18, 18)
                .addGroup(JbodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoUnHDNCC)
                    .addComponent(rdoHDNCC)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        JbodyLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnClearNCC, btnClearNXB, btnDeleteNCC, btnInsertNCC, btnInsertNXB, btnShowAll, btnUpdateNCC, btnUpdateNXB});

        txtTenNXB.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbody, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jbody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblNCC2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCC2MouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblNCC2.getSelectedRow();
            showInforNCC();
            updateStatus();
        }
    }//GEN-LAST:event_tblNCC2MouseClicked

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        if (MsgBox.comfirm(this, "Bạn muốn hiển thị tất cả nhà xuất bản không?")) {
            this.model = (DefaultTableModel) tblNXB.getModel();
            this.model.setRowCount(0); // xoá tất cả các hàng trên Table
            try {
                this.listNXB = daoNXB.selecALLL(); // đọc dữ liệu từ CSDL
                for (NhaXuatBan nxb : listNXB) {
                    // thêm một hàng vào table
                    this.model.addRow(new Object[]{nxb.getTenNhaXB(), nxb.getDiaChi(), nxb.getSDT(), nxb.isTrangThai() == 1 ? "Đang hoạt động" : "Đang ẩn"});
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnDeleteNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNCCActionPerformed
        if (MsgBox.comfirm(this, "Bạn có muốn hiển thị tất cả không?")) {
            this.model = (DefaultTableModel) tblNCC2.getModel();
            this.model.setRowCount(0); // xoá tất cả các hàng trên Table
            try {
                this.list2 = dao2.selecALLL(); // đọc dữ liệu từ CSDL
                for (NhaCungCap ncc : list2) {
                    // thêm một hàng vào table
                    this.model.addRow(new Object[]{ncc.getTenNhaCP(), ncc.getDiaChi(), ncc.getSDT(), ncc.isTrangThai() == 1 ? "Đang hoạt động" : "Đang ẩn"});
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteNCCActionPerformed

    private void btnClearNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNCCActionPerformed
        if (MsgBox.comfirm(this, "Bạn có muốn làm mới form?")){
        resetColorNCC();
        clearFormNCC();
        txtTenNCC.requestFocus();
        }
    }//GEN-LAST:event_btnClearNCCActionPerformed

    private void btnUpdateNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNCCActionPerformed
        if (MsgBox.comfirm(this, "Bạn chắc chắn muốn sửa không?")) {
            if (XHeper.checkNullText(txtTenNCC) && XHeper.checkNullText(txtDiachiNCC) && XHeper.checkNullText(txtSDTNCC) && XHeper.checkSDTALL(txtSDTNCC)) {
                updateNCC();
            }
        }
    }//GEN-LAST:event_btnUpdateNCCActionPerformed

    private void btnInsertNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNCCActionPerformed
        if (MsgBox.comfirm(this, "Bạn muốn thêm Nhà cung cấp không?")) {
            resetColorNCC();
            if (XHeper.checkNullText(txtTenNCC) && XHeper.checkNullText(txtDiachiNCC) && XHeper.checkNullText(txtSDTNCC) && XHeper.checkSDTALL(txtSDTNCC)) {
                insertNCC();
            }
        }
    }//GEN-LAST:event_btnInsertNCCActionPerformed

    private void rdoHDNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHDNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHDNCCActionPerformed

    private void txtSDTNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNCCActionPerformed

    private void txtDiachiNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiachiNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiachiNCCActionPerformed

    private void txtTenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNCCActionPerformed

    private void btnUpdateNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNXBActionPerformed
        if (MsgBox.comfirm(this, "Bạn chắc chắn muốn sửa không?")) {
            if (XHeper.checkNullText(txtTenNXB) && XHeper.checkNullText(txtDiachiNXB) && XHeper.checkNullText(txtSDTNXB) && XHeper.checkSDTALL(txtSDTNXB)) {
                updateNXB();
            }
        }
    }//GEN-LAST:event_btnUpdateNXBActionPerformed

    private void btnInsertNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNXBActionPerformed
        if (MsgBox.comfirm(this, "Bạn muốn thêm Nhà xuất bản không?")) {
            resetColorNXB();
            if (XHeper.checkNullText(txtTenNXB) && XHeper.checkNullText(txtDiachiNXB) && XHeper.checkNullText(txtSDTNXB) && XHeper.checkSDTALL(txtSDTNXB)) {
                insertNXB();
            }
        }
    }//GEN-LAST:event_btnInsertNXBActionPerformed

    private void btnClearNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearNXBActionPerformed
        if (MsgBox.comfirm(this, "Bạn có muốn làm mới form?")){
        resetColorNXB();
        clearFormNXB();
        txtTenNXB.requestFocus();
        }
    }//GEN-LAST:event_btnClearNXBActionPerformed

    private void txtTenNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNXBActionPerformed

    private void txtDiachiNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiachiNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiachiNXBActionPerformed

    private void txtSDTNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTNXBActionPerformed

    private void rdoUnHDNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoUnHDNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoUnHDNXBActionPerformed

    private void rdoHDNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHDNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHDNXBActionPerformed

    private void tblNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNXBMouseClicked
        if (evt.getClickCount() == 2) {
            resetColorNXB();
            this.index = tblNXB.getSelectedRow();
            showInforNXB();
            updateStatus();
        }
    }//GEN-LAST:event_tblNXBMouseClicked

    private void fillTableNXB() {
        this.model = (DefaultTableModel) tblNXB.getModel();
        this.model.setRowCount(0); // xoá tất cả các hàng trên Table
        try {
            this.listNXB = daoNXB.selecALL(); // đọc dữ liệu từ CSDL
            for (NhaXuatBan nxb : listNXB) {
                // thêm một hàng vào table
                this.model.addRow(new Object[]{nxb.getTenNhaXB(), nxb.getDiaChi(), nxb.getSDT(), nxb.isTrangThai() == 1 ? "Đang hoạt động" : "Đang ẩn"});
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }

    private void fillTableNCC() {
        this.model = (DefaultTableModel) tblNCC2.getModel();
        this.model.setRowCount(0); // xoá tất cả các hàng trên Table
        try {
            this.list2 = dao2.selecALL(); // đọc dữ liệu từ CSDL
            for (NhaCungCap ncc : list2) {
                // thêm một hàng vào table
                this.model.addRow(new Object[]{ncc.getTenNhaCP(), ncc.getDiaChi(), ncc.getSDT(), ncc.isTrangThai() == 1 ? "Đang hoạt động" : "Đang ẩn"});
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void updateNXB() {
        NhaXuatBan nxb = getFormNXB();
        try {
            daoNXB.update(nxb);
            fillTableNXB();
            if (rdoHDNXB.isSelected()) {
                tblNXB.setRowSelectionInterval(index, index);
            }
            MsgBox.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");
        }
    }

    private void updateNCC() {
        NhaCungCap ncc = getFormNCC();
        try {
            dao2.update(ncc);
            fillTableNCC();
            if (rdoHDNCC.isSelected()) {
                tblNCC2.setRowSelectionInterval(index, index);
            };
            MsgBox.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại");
        }
    }

    private void updateStatus() {
        boolean edit = (this.index >= 0);

        // Trạng thái form NXB
        this.txtTenNXB.setEditable(!edit);
        this.btnInsertNXB.setEnabled(!edit);
        this.btnUpdateNXB.setEnabled(edit);
        this.btnClearNXB.setEnabled(edit);

        //Trạng thái form NCC
        this.txtTenNCC.setEditable(!edit);
        this.btnInsertNCC.setEnabled(!edit);
        this.btnUpdateNCC.setEnabled(edit);
        this.btnClearNCC.setEnabled(edit);
    }

    private void clearFormNXB() {
        NhaXuatBan nxb = new NhaXuatBan();
        this.setForm(nxb);
        this.index = -1;
        this.updateStatus();
    }

    private void clearFormNCC() {
        NhaCungCap ncc = new NhaCungCap();
        this.setFormNCC(ncc);
        this.index = -1;
        this.updateStatus();
    }

    private void insertNXB() {
        NhaXuatBan nxb = this.getFormNXB();
        try {
            this.daoNXB.insert(nxb);
            this.fillTableNXB();
            this.clearFormNXB();
            MsgBox.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
        }
    }

    private void insertNCC() {
        NhaCungCap ncc = this.getFormNCC();
        try {
            this.dao2.insert(ncc);
            this.fillTableNCC();
            this.clearFormNCC();
            MsgBox.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại");
        }
    }

    private void resetColorNXB() {
        txtTenNXB.setBackground(Color.WHITE);
        txtDiachiNXB.setBackground(Color.WHITE);
        txtSDTNXB.setBackground(Color.WHITE);
    }

    private void resetColorNCC() {
        txtTenNCC.setBackground(Color.WHITE);
        txtDiachiNCC.setBackground(Color.WHITE);
        txtSDTNCC.setBackground(Color.WHITE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jbody;
    private javax.swing.JButton btnClearNCC;
    private javax.swing.JButton btnClearNXB;
    private javax.swing.JButton btnDeleteNCC;
    private javax.swing.JButton btnInsertNCC;
    private javax.swing.JButton btnInsertNXB;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUpdateNCC;
    private javax.swing.JButton btnUpdateNXB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JRadioButton rdoHDNCC;
    private javax.swing.JRadioButton rdoHDNXB;
    private javax.swing.JRadioButton rdoUnHDNCC;
    private javax.swing.JRadioButton rdoUnHDNXB;
    private javax.swing.JTable tblNCC2;
    private javax.swing.JTable tblNXB;
    private javax.swing.JTextField txtDiachiNCC;
    private javax.swing.JTextField txtDiachiNXB;
    private javax.swing.JTextField txtSDTNCC;
    private javax.swing.JTextField txtSDTNXB;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTenNXB;
    // End of variables declaration//GEN-END:variables

}
